version: '3.9'

services:
  backend:
    container_name: post-backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: compose-post-backend-opti
    ports: 
      - 4000:3000
    restart: on-failure
    env_file: 
      - .env 

  frontend:
    container_name: post-frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: compose-post-frontend-opti
    ports: 
      - 8081:80
    restart: on-failure

  postgres:
    container_name: post-postgres
    volumes:
      - postgres_data:/data/postgres
    image: postgres
    restart: on-failure
    env_file: 
      - .env 
    

volumes: 
  postgres_data:
